MY_OAUTHCONSUMER_SECRET = "YOUR OAUTH_CONSUMER_SECRET"
APP_NAME = "your app name id"
PRETTY_APP_NAME="your app name"
PRETTY_APP_PHONE="Tropo number that starts your app"
GOOGLE_VERIFY_FILE = "domain validation html file"
